---
name: terraform-validate

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage
  issue_comment:
    types: [created]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: ./